### ISSUE TITLE
The type and number of GPUs used for training, and whether Isaac Gym is headless or not.

### ISSUE THREAD

**Issue by dinnno** [contact-non-prehensile/corn#1]
I impressed with the research and interested in reproducing the code. According to the paper, the training was conducted over approximately one day using 4096 parallel environments. To clarify your inquiries:

1. What type and number of GPUs were used for the training?
2. Was the headless mode feature of Isaac Gym utilized during the training?

**Comment by Bailey-24** [comment]
hello, 
I use just one 3090.
![image](https://github.com/user-attachments/assets/9c990ed6-778c-4e51-adbc-ee702e7d24dc)
It takes 4 days.
![image](https://github.com/user-attachments/assets/c02b8239-4b73-4acf-afe3-39ff38655e90)

What number of GPUs were used for the training the policy?

**Comment by yycho0108** [comment]
> I impressed with the research and interested in reproducing the code. According to the paper, the training was conducted over approximately one day using 4096 parallel environments. To clarify your inquiries:
> 
> 1. What type and number of GPUs were used for the training?
> 2. Was the headless mode feature of Isaac Gym utilized during the training?
1. 1 NVIDIA A6000 GPU
2. Yes.

> hello, I use just one 3090. 
> What number of GPUs were used for the training the policy?

We used 1 NVIDIA A6000 GPU for training the policy.

@Bailey-24  As for the training time, the number of training steps in the released code is configured by default to be 2M, which corresponds to 8G interaction steps (since there are 4096 envs running in parallel). 8G is about 4x the number of required steps for convergence, since the policy performance saturates around 2G interactions. This would take around 1~2 days, depending on your hardware, at which point you can terminate the training.
